### ISSUE TITLE
Proposal for FuelPHP site

### ISSUE THREAD

**Issue by dmyers** [fuel/fuelphp.com#3]
What do you all think of making FuelPHP.com use the Fuel 1.2.1 framework along with maybe [Bootstrap](http://github.com/dmyers/fuel-bootstrap) and Vanilla for forums and also have a packages module where people can view popular packages to use and get the community growing.

We discussed the packages viewing on Twitter a while back, but wondered what your guys' thoughts on the main site where. I also think Vanilla is a great minimal forum.

**Comment by jschreuder** [comment]
We are working on something along those lines. The fuel/depot repo is the website that is meant to replace our current website. I think @Wanwizard is already planning to use Vanilla for the forums, but that'll be phase 2 after Depot has been launched.

**Comment by WanWizard** [comment]
Correct. 

And there's still a lot of work to be done. Apart from the already defined but empty modules in Depot we also need something to replace the current blog/news module, and perhaps something to create static pages to replace the static views currently used.

Depot is in a public repo, so if you like to chip in, pull request!

**Comment by dmyers** [comment]
Oh okay awesome guys. I guess I have that repo as watched and forgot about it, will try to help! Thanks.
